### ISSUE TITLE
Is this project going to participate for Hacktoberfest ?

### ISSUE THREAD

**Issue by hasnainmakada-99** [Dun-sin/Sporely#1]

**Comment by Dun-sin** [comment]
Depends on when I'm done with the mvp

**Comment by hasnainmakada-99** [comment]
Mvp ?

**Comment by Dun-sin** [comment]
Minimum Valuable Product which means the base feature of an app

**Comment by hasnainmakada-99** [comment]
Okk, but is going to participate right ?

**Comment by Dun-sin** [comment]
> Okk, but is going to participate right ?

Depends on when I'm done with the mvp, I just said that

**Comment by hasnainmakada-99** [comment]
Okay
